travis:
  secure:
    BINSTAR_TOKEN: WmOzGPjBmiuRhO22OyEuQzANILrl0NrnBSUSW18T/dYYpWxetdotTqIyg9Uso4IgARcNpGJtHvmgmudjSzsPe55siZeCJtdJ155Ogw5InfppUmL5xQ7op0KJDU/M2RtawACsCrvLcisqtJmhVNKjuVwNu3I+dOb1qVtmbdSVFyr7tJCQ0/eGzCok9JnvIY8aKBSFA9ypc86zwRDty2gIJVQyGF6s/kBYIttTEshq3yjrfeWwM3IRDWZrZgDuQAPxY7OaN2lXNBjke9yQ8taRRlraK2RV6WdgI3h4bW9aKUmJep5oT+CEjM+4eTmdESQ7dAY1bNPQ/a4UYrQkWSmd6ngNjLaWINOO1o9Z2y7TqUkEsAdxv42oy1wkCxEqzj3UAOZrWbLWSUzkpvg1il1+vUfjnanRIQM7yMFZawYGOhWWvFcm805EeUYz7W/mYIVBq/KL1X2ClJlzzSUEXQiQP6Cj+ibkKEC4qcqUJPokf7xNEzptJK6d/SJI2z9oj9rDgbMn0fMZhMK5/0M8ADK+ObmkswGbP51Pk7FqNzX8NPhBo02mXNzXIYIiFE1+7SlUxPsWvzssi0PHXaaTZqqblyMBpCi72VoZwNOGpPFYAoRSdikfjqrNff7fvv6tGxdM9WsDE8Ds+4iy/tcO+cTI9hzikzRQ4DYYQNxsOI3SUZg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
