travis:
  secure:
    BINSTAR_TOKEN: qVEfDGh8QIq+szjamOtGlF70lMtfgU9Bx7ZrDKAa/oKsQpgll3d3OABsLyZxqZovbN/IvHD7YpaBdxhIA5gBGD0hjsrEdHj6NdZ9dAeRovtLd05BQeC4rAnEu+y6lqIJuryY0t8i8sZ0UCn5uXvLkfLzHF1rLWtHeLxzNxZVBcE8MBPRBXzDPT4J2h5WynOZbZO8jxfhiJRqOazAxKDc50AxstcyHGJuM13LTpkacKwGiV5hkGXWmUYLRYPr7N9qI7dz49/0aR9mbMz69jzRWKcb+8PUYOtL4N7GUXoyXUJGYtYUnkURoTyvi95hEGoO+WRkvTgHImbvnAOGTJl494kPLdcPeR6y5haRL8QHGS9a22+3bjC156miN5KrgAQtRUEBDehdNUlD1AgGKmnu0JJt1Ef6Scg9DtQhtFRLQzVSt4/OZhhdj/GOBW+dOwCE8dauKqaBl6foz/BWl3NokIB31JOdluLVUj68ZCif9dJS7Vn8yPX3x0VgYUEeiwcr3b6yMwFySjkgeGjTCDsjV2vjUrGHsiI9nHXb8FfAmXvEsYhMDYh8qE6laOQVgkC+K3UM7PRilaPbeNbD3W/epg1Xs0LTOjM9ihtgg+yxpnQgHxjzuk49OiBJHnUyJl5+eQLHejl6nI1OSji900H6DGguEY5QcINf5BghEq9XjQY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
